'use strict';
// All flower sizes, toilet queues, driving and collisions are authoritative.
module.exports=({getGame,G,sim,broadcast,changed,save,message,clock=Date.now,random=Math.random})=>{
 const ps=()=>Object.values(getGame().players).filter(p=>!p.kicked),dist=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z),sink={x:-30,z:-18},stalls=[5,9,13].map(x=>({x,z:-24.4}));
 const props=[...[-33,-21,21,33].map(x=>({id:'patio:'+x+':49',kind:'table',x,z:49,r:2.3})),...[47,58].flatMap(x=>[-32,-18,-4].map(z=>({id:'tree:'+x+':'+z,kind:'tree',x,z,r:1.8}))),...[-51,-38,-24,-10,5,21,37,53].flatMap(x=>[-53,-40].map(z=>({id:'tree:'+x+':'+z,kind:'tree',x,z,r:1.3})))];
 function state(){const g=getGame();return g.play||(g.play={flowers:{},queue:[],cars:[{id:'car-1',x:-20,z:57,angle:Math.PI/2,driver:null,path:[]},{id:'car-2',x:20,z:57,angle:Math.PI/2,driver:null,path:[]}],props:{}});}
 function person(p){if(!p.play||p.play.gameId!==getGame().gameId)p.play={gameId:getGame().gameId,toilet:{phase:'waiting',taps:0},nickname:'',cuffUntil:0};return p.play;}
 function view(p){const q=person(p);return{toilet:{...q.toilet},nickname:q.nickname,cuffUntil:q.cuffUntil,arrestUntil:q.arrestUntil||0,arrestFrom:q.arrestFrom||null,carId:q.carId||null,flower:q.flower||null};}
 function summary(){const s=state();return{flowers:Object.values(s.flowers),flowerTop:Object.values(s.flowers).filter(f=>ps().some(p=>p.id===f.id)).sort((a,b)=>b.height-a.height||a.at-b.at).slice(0,5),queue:s.queue,cars:s.cars.map(c=>({...c,path:undefined})),props:s.props,players:ps().map(p=>({id:p.id,...view(p)}))};}
 function event(kind,p,text,data={}){broadcast({t:'play.fx',kind,by:p?.id,text,...data});if(text)message('金桶小劇場',text,'event');}
 const crawling=p=>!!person(p).toilet.collapsed&&person(p).toilet.phase!=='done',needs=p=>['need','crawl','queue','seated'].includes(person(p).toilet.phase);
 function blocked(p,t){if(!p)return false;const q=person(p);if(clock()<(q.arrestUntil||0))return !['input.active','hello','ping'].includes(t)&&!t.startsWith('h.');if(q.carId)return !['office.move','car.exit','car.drive','input.active','chat.send','hello','ping'].includes(t)&&!t.startsWith('h.');return crawling(p)&&!['toilet.go','toilet.tap','office.move','input.active','hello','ping'].includes(t)&&!t.startsWith('h.');}
 function toiletGo(p){const q=person(p);if(q.toilet.phase==='done')return false;if(!needs(p))return false;if(q.carId)exitCar(p);p.distraction=null;p.expelPending=false;p.indoorBanUntil=0;if(!state().queue.includes(p.id))state().queue.push(p.id);if(p.motion?.room!=='wc'&&p.motion?.destination!=='wc')sim.travel(p,'wc',{x:9,z:-16});return true;}
 function exitCar(p){const q=person(p),c=state().cars.find(c=>c.driver===p.id);if(!c){q.carId=null;return;}c.driver=null;c.path=[];q.carId=null;const candidates=[{x:c.x,z:c.z+3},{x:c.x,z:c.z-3},{x:c.x+3,z:c.z},{x:c.x-3,z:c.z}];const spot=candidates.find(v=>sim.nav.walkable(v,p.rank==='boss')&&ps().every(o=>o===p||!o.motion||dist(o.motion,v)>1.4));if(spot)Object.assign(p.motion,spot);p.motion.room='grounds';p.motion.destination=null;p.motion.path=[];changed();}
 function driveable(p){return Number.isFinite(p.x)&&Number.isFinite(p.z)&&Math.abs(p.x)<=61&&p.z>=-56&&p.z<=71&&!(Math.abs(p.x)<43&&p.z> -32&&p.z<46)&&!(p.x>40&&p.z>14&&p.z<42);}
 function segment(a,b){const n=Math.max(1,Math.ceil(dist(a,b)/.7));for(let i=0;i<=n;i++)if(!driveable({x:a.x+(b.x-a.x)*i/n,z:a.z+(b.z-a.z)*i/n}))return false;return true;}
 function route(a,b){if(!driveable(b))return null;if(segment(a,b))return[[b.x,b.z]];const nodes=[a,b,...[-46,46].flatMap(x=>[-35,48,66].map(z=>({x,z})))].filter(p=>driveable(p));const d=nodes.map(()=>Infinity),prev=[],todo=new Set(nodes.map((_,i)=>i));d[0]=0;while(todo.size){let i=[...todo].sort((i,j)=>d[i]-d[j])[0];todo.delete(i);if(!Number.isFinite(d[i])||i===1)break;for(const j of todo)if(segment(nodes[i],nodes[j])){const v=d[i]+dist(nodes[i],nodes[j]);if(v<d[j]){d[j]=v;prev[j]=i;}}}if(!Number.isFinite(d[1]))return null;const out=[];for(let i=1;i!==0;i=prev[i])out.unshift([nodes[i].x,nodes[i].z]);return out;}
 function handle(c,m){if(!['flower.plant','toilet.go','toilet.tap','car.enter','car.exit','car.drive'].includes(m.t))return false;const p=c.player;if(!p||p.kicked){c.reply({t:'err',msg:'先報到，再來玩。'});return true;}const q=person(p),now=clock();if(getGame().pausedRemaining!=null){c.reply({t:'err',msg:'主持人已暫停，稍等一下。'});return true;}if(blocked(p,m.t)){c.reply({t:'err',msg:'先處理眼前的突發任務！'});return true;}
  if(m.t==='flower.plant'){if(p.motion.room!=='lounge'||dist(p.motion,sink)>4.2){c.reply({t:'err',msg:'請走到茶水間洗手槽旁邊再種花。'});return true;}if(now<(q.plantReady||0))return true;q.plantReady=now+1800;const height=Math.round((.35+random()**2*4.65)*100),f={id:p.id,name:p.name,height,color:Math.floor(random()*5),at:now,slot:p.joinIdx-1};q.flower={height,at:now};if(!state().flowers[p.id]||height>state().flowers[p.id].height)state().flowers[p.id]=f;q.nickname=height>=400?'盆栽界的巨人':height<100?'迷你花農':'帶薪園藝師';event('flower',p,`${p.name} 種出 ${height} 公分的花！`,{height});}
  if(m.t==='toilet.go'){if(!toiletGo(p))c.reply({t:'err',msg:q.toilet.phase==='done'?'今天已經順利解放過了。':'現在還不需要上廁所。'});}
  if(m.t==='toilet.tap'){const t=q.toilet;if(!needs(p))return true;toiletGo(p);if(t.slot==null||p.motion.room!=='wc'||dist(p.motion,stalls[t.slot])>1.85){c.reply({t:'err',msg:'先到廁所排隊，輪到自己的馬桶再點三下。'});return true;}if(now<(t.readyAt||0))return true;t.phase='seated';t.readyAt=now+650;t.taps++;event('poop',p,'',{tap:t.taps});if(t.taps>=3){t.phase='done';t.collapsed=false;delete t.deadline;delete t.slot;state().queue=state().queue.filter(id=>id!==p.id);q.nickname='三響畢業生';event('relief',p,`${p.name}：噗噗噗，這次終於準時交付。`);sim.travel(p,'atrium');}}
  if(m.t==='car.enter'){const car=state().cars.find(x=>x.id===m.carId);if(!car||car.driver||q.carId||p.arrival?.stage!=='done'||!p.motion||dist(p.motion,car)>5||now<q.cuffUntil||needs(p)){c.reply({t:'err',msg:'走近空車才能開車；先完成如廁或手銬倒數。'});return true;}car.driver=p.id;car.path=[];q.carId=car.id;q.nickname='停車場舒馬赫';Object.assign(p.motion,{x:car.x,z:car.z,room:'grounds',destination:null,path:[]});p.distraction=null;event('engine',p,'');}
  if(m.t==='car.exit')exitCar(p);
  if(m.t==='car.drive'){const car=state().cars.find(x=>x.driver===p.id),path=car&&route(car,{x:m.x,z:m.z});if(!path){c.reply({t:'err',msg:'汽車只走戶外道路與露台，不能開進辦公室或泳池。'});return true;}car.path=path;}
  changed();save();return true;
 }
 let previous=clock(),frameAt=0,lastFrame='';
 function tick(){const now=clock(),elapsed=Math.max(0,now-previous),dt=Math.min(.15,elapsed/1000);previous=now;const s=state(),players=ps();if(getGame().pausedRemaining!=null){for(const p of players){const q=person(p);for(const o of[q,q.toilet])for(const k of['dueAt','deadline','readyAt','plantReady','cuffUntil','arrestUntil','claimAt'])if(o[k]>now-elapsed)o[k]+=elapsed;}return;}
  for(const p of players){sim.init?.(p);const q=person(p),t=q.toilet;if(!t.dueAt&&t.phase==='waiting'&&['build','review','poster','gallery'].includes(getGame().phase))t.dueAt=now+12000+Math.floor(random()*78000);if(t.phase==='waiting'&&t.dueAt<=now){t.phase='need';t.deadline=now+30000;q.nickname='膀胱倒數工程師';event('urgent',p,`${p.name} 收到臨時任務：30 秒內去廁所報到！`);changed();}if(t.phase==='need'&&t.deadline<=now){t.phase='crawl';t.collapsed=true;p.motion.path=[];p.motion.destination=null;p.distraction=null;if(q.carId)exitCar(p);q.nickname='地板巡檢總監';event('collapse',p,`${p.name} 趴下了，只能爬去廁所拯救自己。`);changed();}if(needs(p)&&p.motion?.room==='wc'&&!s.queue.includes(p.id))s.queue.push(p.id);}
  for(const p of players){const t=person(p).toilet;if(t.slot!=null&&((!p.online&&!p.bot&&!p.aiControlled)||t.phase!=='seated'&&now-(t.claimAt||now)>25000||p.motion?.room!=='wc'&&p.motion?.destination!=='wc')){delete t.slot;t.phase=t.collapsed?'crawl':'need';t.deadline=now+30000;}}
  s.queue=s.queue.filter(id=>players.some(p=>p.id===id&&needs(p)));const used=new Set(players.filter(p=>needs(p)&&person(p).toilet.slot!=null).map(p=>person(p).toilet.slot));for(const id of s.queue){const p=getGame().players[id],t=person(p).toilet;if(p.motion?.room!=='wc'||!p.online&&!p.bot&&!p.aiControlled)continue;if(t.slot==null){const free=stalls.findIndex((_,i)=>!used.has(i));if(free>=0){used.add(free);t.slot=free;t.phase=t.phase==='crawl'?'crawl':'queue';t.claimAt=now;sim.travel(p,'wc',stalls[free]);changed();}}if(t.slot!=null&&dist(p.motion,stalls[t.slot])<1.85){if(t.phase!=='seated'){t.phase='seated';t.readyAt=0;changed();}if(now-(t.claimAt||now)>18000){t.phase=t.collapsed?'crawl':'queue';delete t.slot;s.queue=s.queue.filter(x=>x!==p.id).concat(p.id);sim.travel(p,'wc',{x:3+(p.joinIdx%7)*1.5,z:-16});changed();}}}
  for(const car of s.cars){let p=players.find(p=>p.id===car.driver);if(!p){car.driver=null;car.path=[];continue;}const q=person(p);if(!p.online&&!p.bot&&!p.aiControlled||needs(p)){exitCar(p);continue;}if(!car.path?.length)continue;const target={x:car.path[0][0],z:car.path[0][1]},d=dist(car,target),move=Math.min(d,dt*24),vx=(target.x-car.x)/(d||1),vz=(target.z-car.z)/(d||1);car.angle=Math.atan2(vx,vz);for(let i=0;i<Math.ceil(move/.4);i++){const step=move/Math.ceil(move/.4),next={x:car.x+vx*step,z:car.z+vz*step};if(!driveable(next)){car.path=[];break;}if(s.cars.some(o=>o!==car&&dist(o,next)<3)){car.path=[];break;}const hit=players.find(o=>o!==p&&o.motion&&!person(o).carId&&dist(o.motion,next)<1.7);if(hit){exitCar(p);q.arrestUntil=now+2400;q.cuffUntil=now+62400;q.nickname='一分鐘慢行大師';q.arrestFrom={x:car.x,z:car.z};event('arrest',p,`OMNI 把 ${p.name} 拖下車上手銬：撞到 ${hit.name}，慢行 60 秒！`);break;}car.x=next.x;car.z=next.z;Object.assign(p.motion,{x:car.x,z:car.z});for(const prop of props)if(dist(prop,car)<prop.r+1&&!(s.props[prop.id]?.until>now)){s.props[prop.id]={until:now+8000,at:now,dx:vx*4,dz:vz*4};event('crash',p,'',{prop:prop.id});}}if(car.driver&&d<=move)car.path.shift();}
  if(now-frameAt>200){frameAt=now;const snapshot=summary(),key=JSON.stringify(snapshot);if(key!==lastFrame){lastFrame=key;broadcast({t:'play.frame',s:snapshot});}}
 }
 function bot(p,send){const q=person(p),t=q.toilet,now=clock();if(needs(p)){if(t.phase==='seated')send({t:'toilet.tap'});else toiletGo(p);return true;}if(q.arrestUntil>now)return true;if(q.carId){const car=state().cars.find(c=>c.driver===p.id);if(now>(q.botDriveEnd||0)){send({t:'car.exit'});}else if(!car.path.length)send({t:'car.drive',x:(p.joinIdx%2?1:-1)*50,z:65});return true;}return false;}
 return{summary,person,view,handle,tick,blocked,bot,needs,crawling,driveable,route,props,stalls,sink};
};
