'use strict';
// Server-only arrival, workstation presence and exhibition voting rules.
module.exports=({getGame,G,nav,changed,clock=Date.now})=>{
 const modes=['scooter','car','run','bicycle','horse','crawl'];
 const speeds={scooter:19,car:22,run:11,bicycle:15,horse:17,crawl:7};
 const stations=G.DESKS.map((d,i)=>{const r=G.ROOMS.find(r=>r.id===d.room),seat={x:d.x,z:d.z+1.55};return{...d,id:d.room+'-'+String(G.DESKS.slice(0,i+1).filter(x=>x.room===d.room).length).padStart(2,'0'),seatX:seat.x,seatZ:seat.z};});
 function station(p){if(!p||!['A','B','M'].includes(p.team))return null;const team=Object.values(getGame().players).filter(q=>!q.kicked&&q.team===p.team).sort((a,b)=>a.joinIdx-b.joinIdx);return stations.filter(d=>d.room===p.team)[team.findIndex(q=>q.id===p.id)%stations.filter(d=>d.room===p.team).length];}
 function atStation(p){const d=station(p),m=p?.motion;return !p?.play?.carId&&!p?.play?.toilet?.collapsed&&!!d&&!!m&&m.room===p.team&&!m.path?.length&&!p.expelPending&&!(p.indoorBanUntil>clock())&&Math.hypot(m.x-d.seatX,m.z-d.seatZ)<=1.6;}
 function inBoard(p){const r=G.ROOMS.find(r=>r.id==='board'),m=p?.motion;return !!m&&m.room==='board'&&!m.path?.length&&!p.expelPending&&!(p.indoorBanUntil>clock())&&Math.abs(m.x-r.x)<r.w/2&&Math.abs(m.z-r.z)<r.d/2;}
 function inspect(p){if(!inBoard(p)||getGame().phase!=='review')return false;p.inspection={phaseAt:getGame().phaseStartedAt,readyAt:clock()+1500};changed();return true;}
 function weight(p){return inBoard(p)&&p.inspection?.phaseAt===getGame().phaseStartedAt&&clock()>=p.inspection.readyAt?2:1;}
 function arrive(p){const sign=p.joinIdx%2?1:-1,mode=modes[(p.joinIdx-1)%modes.length],x=sign*(10+(Math.floor((p.joinIdx-1)/2)%13)*4),z=65+Math.floor((p.joinIdx-1)/26)*5;p.arrival={mode,stage:'road',startedAt:clock()};p.motion={layout:G.LAYOUT,x,z,room:'transit',destination:'atrium',path:[[sign*5,z],[sign*5,58]]};}
 function speed(p){if(p.play?.arrestUntil>clock())return 0;if(p.play?.toilet?.collapsed&&p.play.toilet.phase!=='done')return 2.1;if(p.play?.cuffUntil>clock())return 3;return p.arrival?.stage==='road'?speeds[p.arrival.mode]:p.arrival?.stage==='walk'&&p.arrival.mode==='crawl'?5:7;}
 function arrived(p){if(p.arrival?.stage==='road'){p.arrival.stage='walk';p.motion.path=nav.path(p.motion,{x:((p.joinIdx-1)%10-4.5)*1.8,z:34+Math.floor((p.joinIdx-1)/10)*1.8},false)||[];return true;}if(p.arrival?.stage==='walk'){p.arrival.stage='done';p.arrival.finishedAt=clock();}return false;}
 function locked(p){return p.distraction?.until>clock();}
 function enter(p,id){const seconds=id==='arcade'?20:id==='lounge'?30:0;if(seconds&&p.lastEnteredRoom!==id)p.distraction={room:id,until:clock()+seconds*1000,label:id==='arcade'?'機台太好玩了':'八卦還沒聊完'};p.lastEnteredRoom=id;}
 function status(p){const m=p.motion;if(!m)return null;const q=p.play,t=q?.toilet;if(q?.arrestUntil>clock())return{label:"OMNI 拖下車上銬",until:q.arrestUntil,kind:"ban"};if(t&&["need","crawl","queue","seated"].includes(t.phase))return{label:t.phase==="seated"?`點馬桶 ${t.taps}/3`:t.slot!=null?"前往分配的馬桶":t.collapsed?"趴下了！爬去廁所":"快去廁所排隊",until:t.phase==="need"?t.deadline:null,kind:"toilet"};if(q?.carId)return{label:"駕駛中 · 點戶外移動",until:null,kind:"drive"};if(q?.cuffUntil>clock())return{label:"手銬慢行",until:q.cuffUntil,kind:"ban"};if(locked(p))return{label:p.distraction.label,until:p.distraction.until,kind:'distraction'};if(p.indoorBanUntil>clock())return{label:'OMNI 門禁',until:p.indoorBanUntil,kind:'ban'};if(m.path?.length){let distance=0,from=[m.x,m.z];for(const v of m.path){distance+=Math.hypot(v[0]-from[0],v[1]-from[1]);from=v;}return{label:p.arrival?.stage==='road'?'加班報到':`前往${G.ROOMS.find(r=>r.id===m.destination)?.name||'目的地'}`,until:clock()+distance/speed(p)*1000,kind:'travel'};}if(p.mini?.expires>clock())return{label:p.mini.type==='darts'?'射飛鏢':'彈珠台',until:p.mini.expires,kind:'game'};if(p.leisure?.round?.expires>clock())return{label:'機台挑戰',until:p.leisure.round.expires,kind:'game'};const coffee=getGame().recreation?.coffee;if(coffee?.entries?.[p.id]&&!coffee.finished&&coffee.ends>clock())return{label:'泡咖啡比賽',until:coffee.ends,kind:'game'};if(getGame().phase==='build'&&atStation(p))return{label:p.aiControlled?'AI 代班建模':'馬桶建模',until:getGame().phaseEndsAt,kind:'work'};return{label:p.aiControlled?'AI 代班中':p.dancing?'跳舞中':'自由活動',until:null,kind:'idle'};}
 return{station,atStation,inBoard,inspect,weight,arrive,arrived,speed,modes,locked,enter,status};
};
