'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),{chromium}=require('playwright'),{start,KEY,delay}=require('./helpers.cjs');
(async()=>{const app=await start();let browser;const errors=[];try{
 const host=await app.connect({host:true,key:KEY});host.send({t:'h.fillPlayers'});await host.wait(m=>m.t==='state'&&m.s.players.length===50&&m.s.board.chair);
 host.send({t:'h.settings',buildSec:70});host.send({t:'h.phase',phase:'build'});
 browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1512,height:982}});page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{let value;Object.defineProperty(window,'Office',{get:()=>value,set:c=>{value=new Proxy(c,{construct(t,args,n){const o=Reflect.construct(t,args,n);window.__testOffice=o;return o;}});}});});
 await page.goto(app.base+'/screen');await page.waitForSelector('#office canvas');await page.locator('#cameraOmni').click();
 const bounds=await page.evaluate(()=>new Promise(resolve=>{const start=performance.now(),o=window.__testOffice;let min=Infinity,flips=0,frames=0;function frame(){o.omniBody.updateWorldMatrix(true,true);const b=new THREE.Box3().setFromObject(o.omniBody);min=Math.min(min,b.min.y);if(Math.abs(o.omniBody.rotation.x)>.2)flips++;frames++;if(performance.now()-start<21000)requestAnimationFrame(frame);else resolve({min,flips,frames});}frame();}));assert.ok(bounds.flips>0);assert.ok(bounds.min>=.2,'OMNI must stay above floor');await page.screenshot({path:'public/guide-omni.jpg',quality:85});console.log('OMNI floor bounds '+JSON.stringify(bounds));
 await host.wait(m=>m.t==='state'&&m.s.counts.A>=100&&m.s.counts.B>=100);host.send({t:'h.phase',phase:'review'});await delay(2200);host.send({t:'h.settings',posterSec:30});host.send({t:'h.phase',phase:'poster'});await host.wait(m=>m.t==='state'&&m.s.poster.posters.filter(p=>p.hasImg).length>=8);await delay(1500);
 await page.locator('#posterCurtain').click();await delay(3500);await page.screenshot({path:'public/guide-poster-sky.jpg',quality:85});await page.locator('[data-action="posters"][data-value="1"]').click();await delay(1000);await page.screenshot({path:'public/guide-poster-page.jpg',quality:85});await page.locator('[data-action="posters"][data-value="0"]').click();await page.locator('#cameraHome').click();await delay(3500);await page.screenshot({path:'public/guide-poster-overview.jpg',quality:85});
 const projected=await page.evaluate(()=>{const o=window.__testOffice,v=new THREE.Vector3(0,86,-59).project(o.camera);return{top:(1-v.y)/2,posters:Number(o.el.dataset.posterCount)};});assert.ok(projected.top>0&&projected.top<.5);assert.ok(projected.posters>=8);
 await page.setViewportSize({width:390,height:844});await delay(1000);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'public/guide-mobile.jpg',quality:85});
 assert.deepEqual(errors,[]);fs.writeFileSync('artifacts/arrival-polish-verification.json',JSON.stringify({passed:true,bounds,projected,errors,at:new Date().toISOString()},null,2));console.log('PASS final poster layout, mobile and OMNI');
 }finally{await browser?.close();await app.stop();}})().catch(e=>{console.error(e);process.exitCode=1;});
