'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),{chromium}=require('playwright');const{start,join50,KEY,delay}=require('./helpers.cjs'),G=require('../public/shared.js');
(async()=>{const app=await start();let browser,current;const errors=[],shots=[],rec=require('./video.cjs').recorder();try{
 browser=await chromium.launch({headless:true,channel:'msedge',args:[]});
 async function pageFor(token,url=''){if(current)await current.context().close();const context=await browser.newContext({viewport:{width:1512,height:982},deviceScaleFactor:1});if(token)await context.addInitScript(token=>localStorage.setItem('gt_token',token),token);const p=await context.newPage();p.setDefaultTimeout(60000);p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await rec.attach(p);current=p;await p.goto(app.base+url);await p.waitForSelector('#connection:text("ONLINE")');await delay(1600);return p;}
 const shot=async(p,name)=>{await delay(900);await p.screenshot({path:'public/guide-'+name+'.jpg',quality:80});shots.push(name);console.log('Captured '+name);};
 let p=await pageFor();await p.waitForSelector('.look');await p.getByRole('button',{name:'選擇造型 2',exact:true}).click();await shot(p,'welcome');
 const host=await app.connect({host:true,key:KEY}),{peers,state}=await join50(app,host);p=await pageFor(peers[4].you.token);await shot(p,'arrival');
 p=await pageFor(peers[0].you.token);await p.waitForSelector('[data-action="elect"]');assert.equal(await p.locator(`[data-action="elect"][data-value="${peers[0].you.id}"]`).isDisabled(),true);await shot(p,'director');await p.locator(`[data-action="elect"][data-value="${peers[1].you.id}"]`).click();
 peers[1].send({t:'board.vote',candidate:peers[0].you.id,round:state.board.round});peers[2].send({t:'board.vote',candidate:peers[0].you.id,round:state.board.round});await host.wait(m=>m.t==='state'&&m.s.board.chair===peers[0].you.id);
 for(let i=3;i<peers.length;i++)peers[i].send({t:'work.goto'});host.send({t:'h.phase',phase:'brief'});await p.waitForSelector('[data-action="brief"]:not([disabled])');await p.locator('[data-action="brief"][data-value="0"]').click();await shot(p,'chairperson');
 await p.getByRole('button',{name:'前往神秘機房',exact:true}).click();await p.waitForSelector('[data-action="core"]');await p.locator('[data-action="core"]').click();await p.waitForSelector('#coreData .note');await shot(p,'ai-core');
 host.send({t:'h.settings',buildSec:600});host.send({t:'h.phase',phase:'build'});await host.wait(m=>m.t==='state'&&m.s.phase==='build');for(let i=0;i<peers.length;i++)if(state.players[i].team)peers[i].send({t:'office.move',room:state.players[i].team});await host.wait(m=>m.t==='state'&&m.s.players.filter(p=>p.team).every(p=>p.atWorkstation));
 const index=state.players.findIndex(p=>p.rank==='staff'&&p.team==='A'),builder=peers[index];p=await pageFor(builder.you.token);await p.waitForSelector('[data-edit="true"]');
 const cv=p.locator('[data-edit="true"] canvas'),box=await cv.boundingBox();let placed=false;for(const y of[.75,.6,.85]){await cv.click({position:{x:box.width*.5,y:box.height*y}});await delay(300);if(await p.locator('#owned').textContent()!=='0'){placed=true;break;}}assert.ok(placed,'real canvas places a block');
 // All 50 clients use the real placement protocol to construct two toilet prototypes.
 const cells=[];for(let y=0;y<=2;y++)for(let x=5;x<=8;x++)for(let z=4;z<=8;z++)cells.push([x,y,z,0]);for(let x=4;x<=9;x++)for(let z=2;z<=9;z++)cells.push([x,3,z,0]);for(let y=4;y<=5;y++)for(let x=4;x<=9;x++)for(let z=2;z<=9;z++)if(x===4||x===9||z===2||z===9)cells.push([x,y,z,4]);for(let y=4;y<=10;y++)for(let x=4;x<=9;x++)for(let z=9;z<=11;z++)cells.push([x,y,z,y===10?4:0]);
 for(const team of['A','B']){const crew=state.players.map((v,i)=>({v,peer:peers[i],left:G.RANKS[v.rank].budget-(i===index?1:0)})).filter(v=>v.v.team===team);let n=0;for(const [x,y,z,c]of cells){const actor=crew.filter(a=>a.left>0).sort((a,b)=>b.left-a.left)[0];if(!actor)break;actor.peer.send({t:'place',x,y,z,c:team==='B'&&c===4?7:c});actor.left--;if(++n%6===0)await delay(110);}}
 await host.wait(m=>m.t==='state'&&m.s.counts.A>200&&m.s.counts.B>200);await shot(p,'builder');await p.locator('[data-action="expand"]').click();await shot(p,'workbench');await p.locator('[data-action="expand"]').click();
 await p.locator('#chatInput').fill('馬桶快蓋好了！🚽 <b>這是文字</b>');await p.locator('#chatForm button').click();await p.getByRole('log',{name:'公頻訊息'}).getByText('馬桶快蓋好了！🚽 <b>這是文字</b>',{exact:true}).waitFor();assert.equal(await p.locator('.chat-log span b').count(),0);await shot(p,'public-chat');await p.getByRole('button',{name:'前往遊戲室',exact:true}).click();await p.waitForSelector('.personal-status:text("機台太好玩了")');await shot(p,'arcade-lock');await p.getByRole('button',{name:'前往茶水間',exact:true}).click();await p.waitForSelector('.toast:text("才能離開")');await delay(20500);await p.getByRole('button',{name:'前往茶水間',exact:true}).click();await p.waitForSelector('.personal-status:text("八卦還沒聊完")');await shot(p,'lounge-lock');await delay(30500);
 await p.getByRole('button',{name:'平視第 1 組完整作品頁',exact:true}).click();await delay(3500);await shot(p,'projection-front');assert.ok(parseInt(await p.locator('[data-live-count="A"]').textContent())>200);
 await p.getByRole('button',{name:'全景',exact:true}).click();await p.getByRole('button',{name:'前往月光泳池',exact:true}).click();await p.waitForSelector('.sport-hit:not(.hidden)');await builder.wait(m=>m.t==='state'&&m.s.players.find(v=>v.id===builder.you.id)?.motion.room==='pool');builder.send({t:'office.move',room:'pool',x:48,z:28});await host.wait(m=>m.t==='campus.frame'&&m.s.volley.last===builder.you.id);await p.keyboard.press('Space');await shot(p,'pool');await host.wait(m=>m.t==='campus.frame'&&m.s.volley.score[0]>0);await shot(p,'pool-score');
 await p.setViewportSize({width:390,height:844});await p.evaluate(()=>scrollTo(0,0));await delay(2000);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await shot(p,'mobile');
 for(const rank of['manager','lead']){const i=state.players.findIndex(v=>v.rank===rank&&v.team==='A');p=await pageFor(peers[i].you.token);await p.getByText('主管的神來一筆',{exact:true}).click();await p.locator('[data-action="feedback"]').first().click();if(rank==='lead')await p.locator('[data-action="direction"]').click();await shot(p,rank);}
 const late=await app.connect();late.send({t:'join',name:'週會遲到實習生'});const intern=(await late.wait('you')).you;p=await pageFor(intern.token);await shot(p,'intern');
 p=await pageFor(null,'/host?key='+KEY);await p.waitForSelector('#hostControls');await p.locator('#chatInput').fill('主持台：先完成馬桶，再比黃金右腳。');await p.locator('#chatForm button').click();await shot(p,'host');
 p=await pageFor(null,'/screen');await delay(2500);assert.equal(await p.locator('#hostControls').count(),0);await shot(p,'projector');for(const team of['A','B','C']){await p.locator('[data-screen="'+team+'"]').click();await delay(2600);await shot(p,'team-'+team);}
 host.send({t:'h.phase',phase:'review'});p=await pageFor(builder.you.token);await p.locator('[data-action="vote"][data-value="A"]').click();await shot(p,'review');await p.locator('[data-action="room"][data-value="board"]').click();await p.waitForSelector('[data-action="exhibit"]:not([disabled])');await p.locator('[data-action="exhibit"]').click();await p.waitForSelector('#reviewPresence:text("本次投票 2 分")');await p.locator('[data-action="vote"][data-value="A"]').click();await p.waitForSelector('[data-action="vote"]:text("已投票 · 2 分")');await shot(p,'board-exhibit');peers[0].send({t:'bossPick',team:'A'});await host.wait(m=>m.t==='state'&&m.s.review.bossPick==='A');host.send({t:'h.phase',phase:'poster'});await host.wait(m=>m.t==='state'&&m.s.phase==='poster');
 p=await pageFor(builder.you.token);await p.locator('#price').fill('16800');await p.locator('#quote').fill('坐上去就不想開會');await p.locator('#surveyForm button').click();await shot(p,'survey');
 const maker=peers[state.players.findIndex(v=>v.team==='M')];p=await pageFor(maker.you.token);await p.locator('#productName').fill('週會黃金寶座');await p.locator('#slogan').fill('一起加班，一起坐上未來');await p.locator('[data-action="posterPreview"]').click();await p.waitForSelector('#posterPreview:not(.hidden)');await p.locator('[data-action="posterSubmit"]').click();await p.waitForSelector('[data-action="posterSubmit"]:text("重新提交")');await shot(p,'marketing');
 for(const [j,mp]of state.players.filter(v=>v.team==='M').entries()){if(mp.id===maker.you.id)continue;const who=peers.find(q=>q.you.id===mp.id);const img=await(await fetch(app.base+'/poster/'+maker.you.id+'.jpg')).arrayBuffer();who.send({t:'poster',img:'data:image/jpeg;base64,'+Buffer.from(img).toString('base64'),name:'黃金寶座 / '+String(j+1).padStart(2,'0'),slogan:'同一座馬桶，不同的提案',final:true});await delay(150);}await host.wait(m=>m.t==='state'&&m.s.poster.posters.filter(p=>p.hasImg).length>=8);await delay(1200);await p.locator('#posterCurtain').click();await delay(3000);await shot(p,'poster-sky');await p.locator('[data-action="posters"][data-value="1"]').click();await shot(p,'poster-page');await p.locator('#cameraHome').click();await delay(3500);await shot(p,'poster-overview');host.send({t:'h.phase',phase:'gallery'});p=await pageFor(peers[0].you.token);await p.locator('[data-action="aiPrice"]').click();await p.locator('[data-action="gvote"]').first().click();await p.locator('[data-action="gpick"]').first().click();await shot(p,'gallery');host.send({t:'h.phase',phase:'launch'});await p.waitForSelector('.finance-card.profit');await shot(p,'launch');await p.locator('.finance-card').scrollIntoViewIfNeeded();await shot(p,'profit');host.send({t:'h.phase',phase:'gallery'});await p.waitForSelector('#officialPrice');await p.locator('#officialPrice').fill('200000');await p.locator('[data-action="setPrice"]').click();await p.waitForSelector('[data-official-price]:text("200,000")');host.send({t:'h.phase',phase:'launch'});await p.waitForSelector('.finance-card.bankrupt');await p.locator('.finance-card').scrollIntoViewIfNeeded();await shot(p,'bankrupt');
 assert.deepEqual(errors,[]);await current.context().close();current=null;console.log('Encoding actual gameplay video…');const video=await rec.finish(browser,'public/guide-arrival.webm');
 fs.writeFileSync('artifacts/arrival-visual-verification.json',JSON.stringify({passed:true,release:'rog-city-2026.10.06',connections:51,shots,video,checks:['20s-arcade-lock','30s-lounge-lock','onsite-double-vote','poster-sky-gallery','profitable-launch','bankrupt-launch','actual-canvas-placement','two-human-toilet-builds','chair-brief-and-core','manager-and-lead-controls','intern','public-chat-escaped','in-world-three-full-pages','real-pool-contact-and-goal','mobile-390-no-overflow','host-chat','screen-read-only','review','marketing-poster','survey','gallery','launch'],errors,at:new Date().toISOString()},null,2));console.log('Summit roles, campus and recorded guide passed');
 }finally{await browser?.close();await app.stop();}})().catch(e=>{console.error(e);process.exitCode=1;});

