'use strict';
const{test}=require('node:test'),assert=require('node:assert/strict'),G=require('../public/shared.js');
const make=require('../campus.cjs'),navigation=require('../navigation.cjs');
function fixture(){let now=Date.now();const g={players:{},recreation:{football:{x:0,z:1,vx:0,vz:0,score:[0,0],resetAt:0,last:null}}},messages=[];
 const api=make({getGame:()=>g,G,broadcast:m=>messages.push(m),changed:()=>{},save:()=>{},clock:()=>now});api.summary();
 const add=(id,team='A')=>{const p=g.players[id]={id,name:'同仁'+id,title:'設計師',rank:'staff',team,joinIdx:Object.keys(g.players).length+1,online:true,lastActionAt:now,motion:{x:50,z:50,room:'grounds',destination:null,path:[]},leisure:{score:0}};return{player:p,reply:m=>messages.push(m)};};
 return{g,api,messages,add,time:()=>now,advance:ms=>{const end=now+ms;while(now<end){now+=Math.min(25,end-now);api.tick();}}};
}
test('public chat verifies identity, bounds history and text, rate limits, never trusts supplied author',()=>{const f=fixture(),a=f.add('A');f.api.handle(a,{t:'chat.send',name:'董事長',by:'other',text:'<img src=x onerror=alert(1)> 🚽'});assert.equal(f.g.campus.chat[0].name,'同仁A');assert.equal(f.g.campus.chat[0].by,'A');assert.equal(f.g.campus.chat[0].text,'<img src=x onerror=alert(1)> 🚽');f.api.handle(a,{t:'chat.send',text:'too soon'});assert.equal(f.g.campus.chat.length,1);f.advance(1300);f.api.handle(a,{t:'chat.send',text:'🚽'.repeat(140)+'\u202E'});assert.equal(Array.from(f.g.campus.chat[1].text).length,120);for(let i=0;i<65;i++)f.api.message('系統',String(i),'event');assert.equal(f.g.campus.chat.length,60);f.api.handle({reply:m=>f.messages.push(m)},{t:'chat.send',text:'anonymous'});assert.equal(f.messages.at(-1).t,'err');});
test('idle is exactly 30 seconds, assistance is reversible and also covers disconnected humans',()=>{const f=fixture(),a=f.add('A');f.advance(29975);assert.ok(!a.player.aiControlled);f.advance(25);assert.equal(a.player.aiControlled,true);assert.equal(a.player.bot,undefined);f.api.activity(a.player);assert.equal(a.player.aiControlled,false);a.player.online=false;f.advance(29975);assert.equal(a.player.aiControlled,false);f.advance(25);assert.equal(a.player.aiControlled,true);assert.equal(a.player.bot,undefined);});
test('football awards the correct end, records player/title, rejects remote hits and signals breathing light',()=>{const f=fixture(),a=f.add('A');const b=f.g.recreation.football;f.api.handle(a,{t:'sports.hit',game:'football',score:99999});assert.equal(b.vx,0);Object.assign(a.player.motion,{x:-1,z:1,room:'courtyard'});f.api.handle(a,{t:'sports.hit',game:'football'});assert.equal(b.vx,32);assert.equal(b.kickedAt,f.time());a.player.motion.x=50;f.advance(400);assert.deepEqual(b.score,[1,0]);assert.equal(b.scorer.name,'同仁A');assert.equal(b.scorer.title,'設計師');assert.ok(f.messages.some(m=>m.t==='chat'&&m.message.text.includes('進球高手')));f.advance(2300);assert.equal(b.x,0);assert.equal(b.resetAt,0);});
test('ball contact triggers OMNI chase, publicly evicts only the kicker for 120 seconds, then releases',()=>{const f=fixture(),a=f.add('A'),other=f.add('B');const b=f.g.recreation.football,o=f.g.campus.omni;Object.assign(o,{x:2,z:1,path:[[2,1]],mode:'patrol'});Object.assign(a.player.motion,{x:-1,z:1,room:'courtyard'});f.api.handle(a,{t:'sports.hit',game:'football'});a.player.motion.x=-4;f.advance(150);assert.equal(o.mode,'chase');assert.equal(o.target,'A');assert.equal(a.player.expelPending,true);f.advance(3000);assert.ok(a.player.indoorBanUntil>f.time());assert.equal(a.player.motion.z,54);assert.ok(!other.player.indoorBanUntil);const until=a.player.indoorBanUntil;assert.ok(until-f.time()<=120000);const nav=navigation(G);assert.equal(nav.path(a.player.motion,{x:0,z:30},false,true),null);assert.ok(nav.path(a.player.motion,{x:48,z:28},false,true));assert.ok(f.messages.some(m=>m.t==='chat'&&m.message.text.includes('120 秒')));f.advance(until-f.time()-1);assert.ok(a.player.indoorBanUntil);f.advance(1);assert.equal(a.player.indoorBanUntil,0);});
test('volleyball checks proximity and height, crosses the net, awards landing and out-of-bounds to A/B',()=>{const f=fixture(),a=f.add('A'),b=f.g.campus.volley;assert.ok(b.y<=2.8,'initial serve must be reachable');f.api.handle(a,{t:'sports.hit',game:'volley',score:10000});assert.equal(b.last,null);Object.assign(a.player.motion,{x:48,z:28,room:'pool'});b.y=2;f.api.handle(a,{t:'sports.hit',game:'volley'});assert.equal(b.last,'A');assert.ok(b.vx>0&&b.vy>0);a.player.motion.x=44;f.advance(2000);assert.deepEqual(b.score,[1,0]);f.advance(2300);assert.equal(b.last,null);Object.assign(b,{x:60.9,z:28,y:2,vx:6,vy:0,last:'A',lastSide:'A'});f.advance(50);assert.deepEqual(b.score,[1,1]);});
test('indoor ban cannot be bypassed with a grounds coordinate or a route cutting through the office',()=>{const f=fixture(),a=f.add('A');Object.assign(a.player.motion,{x:0,z:54,room:'terrace',layout:G.LAYOUT});a.player.indoorBanUntil=Date.now()+120000;
 const sim=require('../simulation.cjs')({getGame:()=>f.g,G,broadcast:()=>{},stateChanged:()=>{},save:()=>{},computeRoles:()=>{},buildOpen:()=>false,pending:()=>({}),plan:()=>[]});assert.equal(sim.travel(a.player,'A'),false);assert.equal(sim.travel(a.player,'grounds',{x:0,z:30}),false);assert.equal(sim.travel(a.player,'pool',{x:48,z:28}),true);const nav=navigation(G);let last={x:0,z:54};for(const [x,z]of a.player.motion.path){for(let t=0;t<=1;t+=.05)assert.ok(!nav.insideOffice({x:last.x+(x-last.x)*t,z:last.z+(z-last.z)*t}));last={x,z};}
});
