const{chromium}=require('playwright'),{start,join50,KEY,delay}=require('./helpers.cjs'),assert=require('assert/strict'),fs=require('fs');
(async()=>{const app=await start();let browser;const errors=[],checks=[];try{
 const host=await app.connect({host:true,key:KEY}),{peers,state}=await join50(app,host);
 browser=await chromium.launch({channel:'msedge',headless:true});const ctx=await browser.newContext({viewport:{width:1440,height:960}});
 await ctx.addInitScript(token=>{localStorage.setItem('gt_token',token);for(const key of ['Office','ShowDirector']){let v;Object.defineProperty(window,key,{get:()=>v,set:c=>v=new Proxy(c,{construct(t,a,n){const o=Reflect.construct(t,a,n);window['qa'+key]=o;return o;}})});}},peers[18].you.token);
 const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(app.base);await page.waitForFunction(()=>window.qaOffice?.actors.size===50);await page.locator('.org-menu').click();await page.locator('[data-org-close]').click();
 await page.evaluate(()=>{window.audioCalls=[];const old=MeetingAudio.cue.bind(MeetingAudio);MeetingAudio.cue=k=>{audioCalls.push({k,at:Date.now()});old(k);};});
 await delay(1200);assert.equal(await page.locator('.funny-nickname:not([hidden])').count(),0);
 assert.ok(await page.evaluate(()=>[...qaOffice.actors.values()].every(a=>a.tag.querySelector('b').textContent===Organization.rank(a.p)+' '+a.p.name)));await delay(1200);assert.ok(await page.evaluate(()=>[...qaOffice.actors.values()].every(a=>a.tag.querySelector('b').textContent.startsWith(Organization.rank(a.p)))));
 checks.push('50 ordinary nameplates remain one rank-name bar on repeated state updates; no routine titles');
 // Server joins and phase changes are real; visual-only fixture previews scarce earned titles.
 await page.evaluate(()=>{const a=qaOffice.actors.get(qaOffice.me);a.p.honor='高爾夫第一名';qaOffice.animateActor(a,performance.now(),false);});assert.equal(await page.locator('.funny-nickname:not([hidden])').count(),1);await page.screenshot({path:'artifacts/cues-nameplates.png'});
 peers[1].send({t:'board.vote',candidate:peers[0].you.id,round:state.board.round});peers[2].send({t:'board.vote',candidate:peers[0].you.id,round:state.board.round});await host.wait(m=>m.t==='state'&&m.s.board.chair);
 host.send({t:'h.phase',phase:'build'});await page.waitForSelector('.stage-broadcast:not([hidden])');assert.match(await page.locator('.stage-broadcast').innerText(),/一起蓋馬桶/);const shown=Date.now();await page.screenshot({path:'artifacts/cues-stage-broadcast.png'});await page.waitForSelector('.stage-broadcast[hidden]',{state:'attached'});assert.ok(Date.now()-shown>=4400);checks.push('stage switch broadcasts transparently for five seconds, then dismisses without blocking controls');
 // Shorten this isolated game to exercise the actual server-driven last-five seconds.
 const left=await page.evaluate(()=> (qaShowDirector.s.phaseEndsAt-qaShowDirector.now())/1000);host.send({t:'h.time',sec:7-left});await page.waitForFunction(()=>document.body.classList.contains('phase-last-five'));await page.screenshot({path:'artifacts/cues-last-five.png'});await delay(5500);const calls=await page.evaluate(()=>audioCalls.filter(x=>['phase-tick','phase-end'].includes(x.k)));assert.equal(calls.filter(x=>x.k==='phase-tick').length,5);assert.equal(calls.filter(x=>x.k==='phase-end').length,1);checks.push('five distinct gentle second ticks and one closing cue; large last-five countdown');
 host.send({t:'h.phase',phase:'brief'});await page.waitForFunction(()=>qaShowDirector.s.phase==='brief');await page.setViewportSize({width:390,height:844});await page.locator('[data-phone-view=chat]').click();await page.waitForSelector('.stage-broadcast:not([hidden])');assert.ok(await page.locator('.stage-broadcast').isVisible());assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'artifacts/cues-phone-broadcast.png'});
 host.send({t:'h.time',sec:-30});await page.waitForFunction(()=>qaShowDirector.s.brief.stage==='chair');assert.match(await page.locator('.stage-broadcast').innerText(),/董事長拍板/);assert.ok(await page.evaluate(()=>parseInt(document.querySelector('#clock').textContent.split(':')[1])<=10));host.send({t:'h.pause'});await page.waitForFunction(()=>qaShowDirector.s.pausedRemaining!=null);const pausedClock=await page.locator('#clock').innerText();await delay(1200);assert.equal(await page.locator('#clock').innerText(),pausedClock);assert.equal(await page.locator('body').getAttribute('class').then(x=>x.includes('phase-last-five')),false);checks.push('phone chat also receives broadcasts; brief substage clock and pause stay synchronized');
 const hostPage=await ctx.newPage();hostPage.on('pageerror',e=>errors.push(e.message));await hostPage.goto(app.base+'/host?key='+KEY);await hostPage.waitForSelector('#hostCue');assert.match(await hostPage.locator('#showTitle').innerText(),/董事長拍板/);await hostPage.screenshot({path:'artifacts/cues-host.png'});
 const screen=await ctx.newPage();screen.on('pageerror',e=>errors.push(e.message));await screen.goto(app.base+'/screen');await screen.waitForSelector('.stage-broadcast:not([hidden])');checks.push('host and public projector see matching stage broadcast');assert.deepEqual(errors,[]);
 fs.writeFileSync('artifacts/cues-visual-verification.json',JSON.stringify({passed:true,connections:50,checks,audioCalls:calls,errors},null,2));console.log(JSON.stringify({passed:true,checks}));
 }finally{await browser?.close();await app.stop();}})().catch(e=>{console.error(e);process.exitCode=1;});

