'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');const {chromium}=require('playwright');const {start,join50,KEY,delay}=require('./helpers.cjs');
(async()=>{const app=await start();let browser;const errors=[];try{
 browser=await chromium.launch({headless:true,channel:process.platform==='win32'?'msedge':undefined,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});fs.mkdirSync('artifacts',{recursive:true});
 async function pageFor(token,viewport={width:1512,height:982}){const context=await browser.newContext({viewport,deviceScaleFactor:1});if(token)await context.addInitScript(token=>localStorage.setItem('gt_token',token),token);const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('favicon'))errors.push(m.text()+" "+m.location().url);});return page;}
 const landing=await pageFor();await landing.goto(app.base);await landing.waitForSelector('#joinButton');assert.equal(await landing.locator('#joinButton').isDisabled(),true);await delay(1500);await landing.screenshot({path:'artifacts/nexus-welcome.png'});
 await landing.close(); const host=await app.connect({host:true,key:KEY});const {peers,state}=await join50(app,host);const director=await pageFor(peers[0].you.token);await director.goto(app.base);await director.waitForSelector('[data-action="elect"]');assert.equal(await director.locator(`[data-action="elect"][data-value="${peers[0].you.id}"]`).isDisabled(),true);await director.locator(`[data-action="elect"][data-value="${peers[1].you.id}"]`).click();peers[1].send({t:'board.vote',candidate:peers[0].you.id,round:state.board.round});peers[2].send({t:'board.vote',candidate:peers[0].you.id,round:state.board.round});await host.wait(m=>m.t==='state'&&m.s.board.chair===peers[0].you.id);await director.waitForSelector('h2:text("董事長已就位")');await director.screenshot({path:'artifacts/nexus-board.png'});
 await director.close(); host.send({t:'h.settings',buildSec:300});host.send({t:'h.phase',phase:'build'});await host.wait(m=>m.t==='state'&&m.s.phase==='build');
 for(let i=0;i<peers.length;i++){const p=state.players[i];peers[i].send({t:'office.move',room:i<3?'board':i%7===0?'arcade':i%8===0?'lounge':p.team||'atrium'});}await delay(10500);
 const control=await pageFor();await control.goto(app.base+'/host?key='+KEY);await control.waitForSelector('#hostControls');await control.screenshot({path:'artifacts/nexus-host.png'}); await control.goto('about:blank');
 const builderIndex=state.players.findIndex(p=>p.rank==='staff'&&p.team==='A'&&p.joinIdx%7!==1&&p.joinIdx%8!==1);const builder=await pageFor(peers[builderIndex].you.token);await builder.goto(app.base);await builder.waitForSelector('[data-edit="true"]');await builder.screenshot({path:'artifacts/nexus-build.png'});
 // Test actual canvas placement, not a test-only shortcut.
 const canvas=builder.locator('[data-edit="true"] canvas');const box=await canvas.boundingBox();let placed=false;for(const yy of [.75,.6,.85]){await canvas.click({position:{x:box.width*.5,y:box.height*yy}});await delay(250);if(await builder.locator('#owned').textContent()!=='0'){placed=true;break;}}assert.ok(placed,'UI canvas places a real block');
 await builder.locator('[data-action="expand"]').click();assert.equal(await builder.locator('.voxel.expanded').count(),1);await builder.screenshot({path:'artifacts/nexus-workbench.png'});await builder.locator('[data-action="expand"]').click();
 await builder.getByRole('button',{name:'前往遊戲室',exact:true}).click();await builder.waitForSelector('#arcade',{timeout:45000});await builder.locator('[data-action="arcade"][data-value="pulse"]').click();await builder.waitForSelector('.arcade-grid .lit');await delay(800);await builder.locator('.arcade-grid .lit').click();await delay(250);assert.match(await builder.locator('#arcade').innerText(),/10 分/);await builder.screenshot({path:'artifacts/nexus-arcade.png'});
 const phone=builder;await phone.setViewportSize({width:390,height:844});await phone.evaluate(()=>window.scrollTo(0,0));await delay(900);await phone.waitForSelector('#arcade');assert.equal(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await phone.screenshot({path:'artifacts/nexus-mobile.png',fullPage:true});await builder.setViewportSize({width:1512,height:982});await delay(500);
 const before=await builder.locator('#office canvas').screenshot();const bb=await builder.locator('#office canvas').boundingBox();await builder.mouse.move(bb.x+bb.width*.5,bb.y+bb.height*.5);await builder.mouse.down();await builder.mouse.move(bb.x+bb.width*.5+130,bb.y+bb.height*.5+25,{steps:15});await builder.mouse.up();await delay(700);const after=await builder.locator('#office canvas').screenshot();assert.ok(!before.equals(after));await builder.getByRole('button',{name:'全景',exact:true}).click();
 await builder.close();await control.goto(app.base+'/host?key='+KEY);host.send({t:'h.phase',phase:'review'});await control.waitForSelector('[data-action="vote"][data-value="C"]');await control.screenshot({path:'artifacts/nexus-review.png',fullPage:true});await control.close();
 peers[0].send({t:'bossPick',team:'C'});await host.wait(m=>m.t==='state'&&m.s.review.bossPick==='C');host.send({t:'h.phase',phase:'poster'});await host.wait(m=>m.t==='state'&&m.s.phase==='poster');const maker=await pageFor(peers[state.players.findIndex(p=>p.team==='M')].you.token);await maker.goto(app.base);await maker.waitForSelector('#productName');await maker.locator('[data-action="posterPreview"]').click();await maker.waitForSelector('#posterPreview:not(.hidden)');await maker.locator('[data-action="posterSubmit"]').click();await maker.waitForSelector('[data-action="posterSubmit"]:text("重新提交")');await maker.screenshot({path:'artifacts/nexus-poster.png',fullPage:true});
 assert.deepEqual(errors,[]);fs.writeFileSync('artifacts/visual-verification.json',JSON.stringify({passed:true,at:new Date().toISOString(),viewports:['1512x982','390x844'],connections:50,checks:['real-ui-director-ballot','self-vote-disabled','block-canvas-click','expand-workbench','room-navigation','arcade-real-score','camera-drag','no-mobile-overflow','three-team-review','poster-canvas-submit'],errors},null,2));console.log('NEXUS visual acceptance passed');
 }finally{await browser?.close();await app.stop();}})().catch(e=>{console.error(e);process.exitCode=1;});



