'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');const{chromium}=require('playwright');const{start,KEY,delay}=require('./helpers.cjs');
(async()=>{const app=await start();let browser;const errors=[];try{
 browser=await chromium.launch({headless:true,channel:'msedge',args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const ctx=await browser.newContext({viewport:{width:1512,height:982},deviceScaleFactor:1}),page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});let you;const frames=[];page.on('websocket',ws=>ws.on('framereceived',e=>{try{const m=JSON.parse(e.payload);if(m.t==='you')you=m.you;if(m.t==='leisure.frame')frames.push(m.s);if(frames.length>60)frames.shift();}catch{}}));
 await page.goto(app.base);await page.waitForSelector('.look');assert.equal(await page.locator('.look').count(),3);await page.getByRole('button',{name:'選擇造型 2',exact:true}).click();await page.getByRole('button',{name:'角色配色 3',exact:true}).click();const chosen=await page.locator('.look.selected').getAttribute('data-value'),chosenColor=await page.locator('.crew-colors .selected').getAttribute('data-value');await page.screenshot({path:'artifacts/night-welcome.png'});
 const host=await app.connect({host:true,key:KEY});host.send({t:'h.openLobby'});await page.locator('#playerName').fill('加班測試員');await page.waitForFunction(()=>!document.querySelector('#joinButton').disabled);await page.locator('#joinButton').click();await page.waitForSelector('.kite');await delay(500);assert.ok(you);const actor=await app.connect({token:you.token});actor.you=you;let p=actor.welcome.s.players.find(p=>p.id===you.id);assert.equal(p.appearance.lookId,+chosen);assert.equal(p.appearance.colorId,+chosenColor);
 host.send({t:'h.fillPlayers'});const full=(await host.wait(m=>m.t==='state'&&m.s.players.length===50&&m.s.board.chair===you.id)).s;await page.waitForFunction(()=>document.querySelectorAll('.kite').length===50);assert.equal(await page.locator('.kite.senior').count(),full.players.filter(p=>['boss','board','lead','manager'].includes(p.rank)).length);await delay(3000);await page.screenshot({path:'artifacts/night-office-50.png'});
 const arrive=room=>actor.wait(m=>m.t==='state'&&m.s.players.find(p=>p.id===you.id)?.motion.room===room);
 await page.getByRole('button',{name:'前往神秘機房',exact:true}).click();await arrive('core');await delay(900);await page.screenshot({path:'artifacts/night-gb300.png'});
 // Right dragging is a grab: a world anchor follows the pointer down, not up.
 const cv=page.locator('#office canvas'),box=await cv.boundingBox();const anchor=()=>page.locator('.kite-strings path').first().getAttribute('d');const before=await anchor();const oldY=+before.match(/^M[^,]+,([^ ]+)/)[1];await page.mouse.move(box.x+box.width*.48,box.y+box.height*.45);await page.mouse.down({button:'right'});await page.mouse.move(box.x+box.width*.48,box.y+box.height*.45+70,{steps:12});await page.mouse.up({button:'right'});await delay(1100);const after=await anchor(),newY=+after.match(/^M[^,]+,([^ ]+)/)[1];assert.ok(newY>oldY+15,`right drag follows mouse (${oldY} -> ${newY})`);
 await page.getByRole('button',{name:'前往中庭足球場',exact:true}).click();await arrive('courtyard');actor.send({t:'office.move',room:'courtyard',x:0,z:1});await actor.wait(m=>m.t==='leisure.frame'&&(Math.hypot(m.s.football.vx,m.s.football.vz)>20||m.s.football.score.some(n=>n>0)));await delay(500);await page.screenshot({path:'artifacts/night-football.png'});
 await page.getByRole('button',{name:'前往遊戲室',exact:true}).click();await arrive('arcade');await page.getByRole('button',{name:'射飛鏢',exact:true}).click();await page.waitForSelector('#miniCanvas');await delay(800);await page.locator('[data-action="throw"]').click();await page.waitForFunction(()=>document.querySelector('#miniScore').textContent.includes('分'));await page.screenshot({path:'artifacts/night-darts.png'});
 // Leave/re-enter ends the previous round under the normal server rules.
 actor.send({t:'office.move',room:'arcade',x:-12,z:-16});await arrive('arcade');await delay(500);await page.getByRole('button',{name:'彈珠台',exact:true}).click();await page.waitForSelector('.mini-head b:text("PINBALL")');await delay(900);await page.getByRole('button',{name:'左擋板 ←',exact:true}).click();await page.keyboard.press('ArrowRight');await page.screenshot({path:'artifacts/night-pinball.png'});
 await page.getByRole('button',{name:'前往茶水間',exact:true}).click();await arrive('lounge');await page.getByRole('button',{name:'跳舞 / 停下',exact:true}).click();await actor.wait(m=>m.t==='state'&&m.s.players.find(p=>p.id===you.id)?.dancing);await page.getByRole('button',{name:'加入 30 秒咖啡賽',exact:true}).click();let r=frames.at(-1)?.coffee;await delay(1000);r=frames.at(-1).coffee;const end=r.ends;let cups=0;
 while(Date.now()<end-800&&cups<3){const b=page.locator('[data-action="brew"]');if(await b.count()&&await b.isEnabled())await b.click();await delay(260);cups=frames.at(-1)?.coffee?.entries[you.id]?.cups||0;}
 assert.ok(cups>=1);await page.screenshot({path:'artifacts/night-coffee.png'});
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>window.scrollTo(0,0));await delay(1200);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'artifacts/night-mobile.png',fullPage:true});await page.setViewportSize({width:1512,height:982});
 host.send({t:'h.settings',buildSec:180});host.send({t:'h.phase',phase:'build'});await host.wait(m=>m.t==='state'&&m.s.counts.A>5&&m.s.counts.B>5&&m.s.counts.C>5);await page.goto(app.base+'/screen');await page.waitForSelector('.projection-controls');await page.waitForFunction(()=>Array.from(document.querySelectorAll('[data-live-count]')).every(x=>parseInt(x.textContent)>0));const counts=await page.locator('[data-live-count="C"]').textContent();await delay(2000);assert.notEqual(await page.locator('[data-live-count="C"]').textContent(),counts);await page.screenshot({path:'artifacts/night-projector.png'});assert.equal(await page.locator('#hostControls').count(),0);
 assert.deepEqual(errors,[]);fs.writeFileSync('artifacts/night-visual-verification.json',JSON.stringify({passed:true,at:new Date().toISOString(),players:50,checks:['three-outfit-three-color-real-selection','distinct-server-appearance','50-kite-labels','senior-glow','transparent-core','right-pan-follows-pointer','shared-fast-football','UI-dart-throw','UI-pinball-flippers','dance','real-coffee-cup-steps','mobile-no-overflow','three-teams-live-projection','read-only-screen'],errors},null,2));console.log('Night shift visual acceptance passed');
 }finally{await browser?.close();await app.stop();}})().catch(e=>{console.error(e);process.exitCode=1;});
