'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),G=require('../public/shared.js');
function setup(count=1){let now=100000;const game={gameId:'test',phase:'lobby',players:{}},events=[],errors=[];for(let i=0;i<count;i++)game.players['p'+i]={id:'p'+i,name:'同仁'+i,joinIdx:i+1,online:true,rank:'staff',arrival:{stage:'done'},motion:{x:-30,z:-24.5,room:'lounge',path:[]}};const sim={nav:{walkable:()=>true},travel(p,room,point){p.motion.room=room;if(point)Object.assign(p.motion,point);p.motion.path=[];return true;}};const play=require('../play.cjs')({getGame:()=>game,G,sim,clock:()=>now,random:()=>.5,broadcast:m=>events.push(m),changed:()=>{},save:()=>{},message:()=>{}});const p=game.players.p0,send=(m,who=p)=>play.handle({player:who,reply:m=>errors.push(m)},m),advance=ms=>{now+=ms;play.tick();};return{game,play,p,send,advance,events,errors,now:()=>now};}
test('planting validates proximity, server size, cooldown and five-place best leaderboard',()=>{const x=setup(8);x.send({t:'flower.plant',height:999999});assert.equal(x.play.summary().flowerTop[0].height,151);x.send({t:'flower.plant'});assert.equal(x.events.filter(e=>e.kind==='flower').length,1);x.p.motion.x=0;x.advance(2000);x.send({t:'flower.plant'});assert.equal(x.errors.length,1);for(const p of Object.values(x.game.players).slice(1))x.send({t:'flower.plant'},p);assert.equal(x.play.summary().flowers.length,8);assert.equal(x.play.summary().flowerTop.length,5);});
test('one random toilet task, collapse prevents unrelated actions, queue, three paced taps and recovery',()=>{const x=setup();x.game.phase='build';x.advance(1);const due=x.p.play.toilet.dueAt;assert.ok(due>=x.now()+12000&&due<=x.now()+90000);x.advance(51001);assert.equal(x.p.play.toilet.phase,'need');x.advance(30001);assert.ok(x.play.crawling(x.p));assert.ok(x.play.blocked(x.p,'place'));assert.ok(x.play.blocked(x.p,'flower.plant'));x.send({t:'toilet.go'});x.advance(1);assert.equal(x.p.play.toilet.phase,'seated');assert.ok(x.play.blocked(x.p,'chat.send'),'collapsed seated player remains restricted');x.send({t:'toilet.tap'});x.send({t:'toilet.tap'});assert.equal(x.p.play.toilet.taps,1);x.advance(651);x.send({t:'toilet.tap'});x.advance(651);x.send({t:'toilet.tap'});assert.equal(x.p.play.toilet.phase,'done');assert.equal(x.events.filter(e=>e.kind==='poop').length,3);assert.equal(x.play.blocked(x.p,'place'),false);x.advance(1000000);assert.equal(x.p.play.toilet.phase,'done');});
test('three exclusive toilet stalls, fourth queues, released stall is reassigned',()=>{const x=setup(4);for(const p of Object.values(x.game.players)){x.play.person(p).toilet={phase:'need',deadline:x.now()+30000,taps:0};x.send({t:'toilet.go'},p);}x.advance(1);const slots=Object.values(x.game.players).map(p=>p.play.toilet.slot);assert.equal(new Set(slots.filter(v=>v!=null)).size,3);assert.equal(slots[3],undefined);x.send({t:'toilet.tap'});x.advance(651);x.send({t:'toilet.tap'});x.advance(651);x.send({t:'toilet.tap'});x.advance(1);assert.equal(x.game.players.p3.play.toilet.slot,0);});
test('disconnected stall occupant releases the stall',()=>{const x=setup(4);for(const p of Object.values(x.game.players)){x.play.person(p).toilet={phase:'need',deadline:x.now()+30000,taps:0};x.send({t:'toilet.go'},p);}x.advance(1);x.p.online=false;x.p.motion.room='grounds';x.advance(1);assert.equal(x.game.players.p3.play.toilet.slot,0);});
test('pause preserves toilet warning and punishment clocks',()=>{const x=setup();const q=x.play.person(x.p);q.toilet={phase:'need',deadline:x.now()+30000};q.cuffUntil=x.now()+60000;x.game.pausedRemaining=123;x.advance(15000);assert.equal(q.toilet.deadline,x.now()+30000);assert.equal(q.cuffUntil,x.now()+60000);});
test('two cars have exclusive ownership and server validates outdoor route',()=>{const x=setup(2);for(const p of Object.values(x.game.players))Object.assign(p.motion,{x:-20,z:57,room:'road'});x.send({t:'car.enter',carId:'car-1'});x.send({t:'car.enter',carId:'car-1'},x.game.players.p1);assert.equal(x.play.summary().cars[0].driver,'p0');assert.equal(x.game.players.p1.play.carId,undefined);x.send({t:'car.drive',x:0,z:0});assert.equal(x.errors.length,2);assert.equal(x.play.route({x:-20,z:57},{x:20,z:-45})!==null,true);assert.equal(x.play.driveable({x:52,z:28}),false);assert.equal(x.play.driveable({x:NaN,z:50}),false);assert.ok(x.play.blocked(x.p,'place'));});
test('swept driving hits pedestrian, OMNI ejects driver and slow punishment lasts 60 seconds after arrest',()=>{const x=setup(2);Object.assign(x.p.motion,{x:-20,z:57,room:'road'});Object.assign(x.game.players.p1.motion,{x:-15,z:57,room:'road'});x.send({t:'car.enter',carId:'car-1'});x.send({t:'car.drive',x:15,z:57});for(let i=0;i<10;i++)x.advance(50);assert.equal(x.p.play.carId,null);assert.ok(x.p.play.cuffUntil>x.now()+60000);assert.equal(x.events.filter(e=>e.kind==='arrest').length,1);x.advance(2500);assert.ok(x.p.play.cuffUntil>x.now());x.send({t:'car.enter',carId:'car-1'});assert.equal(x.p.play.carId,null);x.advance(60000);assert.ok(x.p.play.cuffUntil<=x.now());});
test('outdoor furniture can be knocked aside with a single sound during its cooldown',()=>{const x=setup();Object.assign(x.p.motion,{x:-20,z:57,room:'road'});x.send({t:'car.enter',carId:'car-1'});x.send({t:'car.drive',x:-21,z:47});for(let i=0;i<20;i++)x.advance(50);assert.ok(x.play.summary().props['patio:-21:49']);assert.equal(x.events.filter(e=>e.kind==='crash').length,1);});
test('AI handles urgent toilet trip and uses same three-tap rules',()=>{const x=setup();x.play.person(x.p).toilet={phase:'need',deadline:x.now()+30000,taps:0};assert.ok(x.play.bot(x.p,m=>x.send(m)));x.advance(1);for(let i=0;i<3;i++){x.play.bot(x.p,m=>x.send(m));x.advance(700);}assert.equal(x.p.play.toilet.phase,'done');});
