'use strict';
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const outputDir=path.resolve(__dirname,'../artifacts');fs.mkdirSync(outputDir,{recursive:true});
const root=path.resolve(process.argv[2]||'.'),tag=process.argv[3]||'quality',isNew=!tag.includes('before'),{start,join50,KEY,delay}=require(path.join(root,'tests/helpers.cjs'));
const watchdog=setTimeout(()=>{console.error("Quality check exceeded 150 seconds");process.exit(2)},150000); (async()=>{console.log("Starting isolated 50-client server");const app=await start();let browser;try{const host=await app.connect({host:true,key:KEY});await join50(app,host);console.log("Launching QA browser");browser=await chromium.launch({channel:'msedge',headless:true});console.log("Creating QA page");const page=await browser.newPage({viewport:{width:1920,height:1080}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.addInitScript(()=>{let v;Object.defineProperty(window,'Office',{get:()=>v,set:c=>v=new Proxy(c,{construct(t,a,n){const o=Reflect.construct(t,a,n);window.__qualityOffice=o;return o;}})});});console.log('Loading scene');await page.goto(app.base+'/screen');await page.waitForSelector('#office canvas');await delay(1800);
console.log("Capturing scene");await page.screenshot({path:path.join(outputDir,tag+'-overview.png')});await page.evaluate(()=>{const o=window.__qualityOffice;o.desiredFocus.set(-20,0,8);o.goal={theta:.3,phi:.8,radius:62};});await delay(1500);console.log("Capturing scene");await page.screenshot({path:path.join(outputDir,tag+'-detail.png')});
const measure=()=>page.evaluate(()=>new Promise(resolve=>{const o=window.__qualityOffice,times=[],start=performance.now();let last=start;function frame(t){times.push(t-last);last=t;if(t-start<5000)return requestAnimationFrame(frame);const sorted=times.slice(1).sort((a,b)=>a-b);resolve({fps:Math.round(times.length*1000/(t-start)),p95:sorted[Math.floor(sorted.length*.95)],ratio:o.renderer.getPixelRatio(),size:[o.renderer.domElement.width,o.renderer.domElement.height],css:[o.el.clientWidth,o.el.clientHeight],actors:o.actors.size,drawCalls:o.renderer.info.render.calls,triangles:o.renderer.info.render.triangles});}requestAnimationFrame(frame);}));const detail=await measure();await page.locator('#cameraHome').click();await delay(1000);const overview=await measure();
await page.locator('#cameraHardwareCity').click();await delay(2000);await page.screenshot({path:path.join(outputDir,tag+'-city.png')});const city=await measure();const scene=await page.evaluate(()=>({buildings:window.__qualityOffice.cityBuildings,logos:window.__qualityOffice.rogLogoCount,signs:window.__qualityOffice.citySignCount,logoLoaded:window.__qualityOffice.rogTexture.image?.naturalWidth===2500}));assert.equal(scene.buildings,30);assert.ok(scene.logos>=15);assert.ok(scene.signs>=25);assert.ok(scene.logoLoaded);if(isNew){assert.ok(overview.ratio>=1.5);await page.locator('#renderQuality').selectOption('ultra');assert.equal(await page.evaluate(()=>window.__qualityOffice.renderer.getPixelRatio()),2);await page.locator('#renderQuality').selectOption('balanced');assert.equal(await page.evaluate(()=>window.__qualityOffice.renderer.getPixelRatio()),1);await page.locator('#renderQuality').selectOption('high');const ratio=await page.evaluate(()=>window.__qualityOffice.renderer.getPixelRatio());const bg=await browser.newPage();await bg.goto('about:blank');await delay(9000);await page.bringToFront();assert.equal(await page.evaluate(()=>window.__qualityOffice.renderer.getPixelRatio()),ratio);await bg.close();await page.reload();await page.waitForSelector('#renderQuality');assert.equal(await page.locator('#renderQuality').inputValue(),'high');await page.setViewportSize({width:2560,height:1440});await delay(1500);assert.ok(await page.evaluate(()=>window.__qualityOffice.renderer.getPixelRatio())>=1);console.log("Capturing scene");await page.screenshot({path:path.join(outputDir,tag+'-2560.png')});await page.setViewportSize({width:390,height:844});await delay(800);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));console.log("Capturing scene");await page.screenshot({path:path.join(outputDir,tag+'-mobile.png')});}
assert.deepEqual(errors,[]);const result={at:new Date().toISOString(),root,connections:50,overview,detail,city,scene,errors,passed:true};fs.writeFileSync(path.join(outputDir,tag+'.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));}finally{await browser?.close();await app.stop();clearTimeout(watchdog);}})().catch(e=>{console.error(e);process.exitCode=1;});


