'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {start,join50,KEY,delay}=require('./helpers.cjs');
test('50 sockets: no self-voting, runoff, navigation, arcade, restricted AI core and complete three-team workflow',{timeout:240000},async t=>{
 const app=await start();t.after(()=>app.stop());const host=await app.connect({host:true,key:KEY});
 assert.equal((await (await fetch(app.base+'/api/info')).json()).release,'rog-city-2026.10.06');
 for(const f of fs.readdirSync(path.join(__dirname,'../public')).filter(f=>f.endsWith('.js')))new vm.Script(fs.readFileSync(path.join(__dirname,'../public',f),'utf8'),{filename:f});
 const {peers,state}=await join50(app,host);assert.equal(state.players.length,50);assert.equal(new Set(state.players.map(p=>p.appearance.lookId)).size,50);assert.equal(new Set(state.players.map(p=>p.appearance.color)).size,50);assert.equal(new Set(state.players.map(p=>p.id)).size,50);assert.deepEqual(state.players.slice(0,3).map(p=>p.rank),['board','board','board']);assert.deepEqual(state.players.slice(3,6).map(p=>p.rank),['lead','lead','lead']);
 let round=state.board.round;const vote=(i,j)=>peers[i].send({t:'board.vote',candidate:peers[j].you.id,round});
 vote(0,0);assert.match((await peers[0].wait('err')).msg,/不能投自己/);
 vote(4,0);assert.match((await peers[4].wait('err')).msg,/三位董事/);
 host.send({t:'h.phase',phase:'build'});assert.match((await host.wait('toast')).msg,/互選董事長/);
 vote(0,1);vote(1,2);vote(2,0);let tied=(await host.wait(m=>m.t==='state'&&m.s.board.tied)).s;assert.equal(tied.board.chair,null);assert.equal(tied.board.round,round+1);round++;
 vote(1,0);vote(2,0);let elected=(await host.wait(m=>m.t==='state'&&m.s.board.chair===peers[0].you.id)).s;assert.equal(Object.keys(elected.board.votes).length,2);assert.equal(elected.players[0].rank,'boss');assert.equal(elected.players[1].rank,'board');
 host.send({t:'h.makeBoss',id:peers[4].you.id});assert.match((await host.wait('err')).msg,/不能指定/);
 const reconnect=await app.connect({token:peers[0].you.token});assert.equal(reconnect.welcome.you.id,peers[0].you.id);assert.equal(reconnect.welcome.s.board.chair,peers[0].you.id);
 const builderIndex=elected.players.findIndex(p=>p.rank==='staff'&&p.team==='A'),builder=peers[builderIndex],manager=peers[elected.players.findIndex(p=>p.rank==='manager'&&p.team==='A')],maker=peers[elected.players.findIndex(p=>p.team==='M')];
 builder.send({t:'office.move',room:'core'});assert.match((await builder.wait('err')).msg,/僅董事長/);builder.send({t:'core.inspect'});assert.match((await builder.wait('err')).msg,/董事長/);
 const arrival=(peer,room)=>peer.wait(m=>m.t==='state'&&m.s.players.find(p=>p.id===peer.you.id)?.motion?.room===room);
 builder.send({t:'office.move',room:'A'});manager.send({t:'office.move',room:'A'});peers[0].send({t:'office.move',room:'core'});await Promise.all([arrival(builder,'A'),arrival(manager,'A'),arrival(peers[0],'core')]);
 peers[0].send({t:'core.inspect'});assert.equal((await peers[0].wait('core.data')).ai.mode,'STANDBY');
 host.send({t:'h.phase',phase:'brief'});await host.wait(m=>m.t==='state'&&m.s.phase==='brief');peers[0].send({t:'brief',choice:1});await host.wait(m=>m.t==='state'&&m.s.brief.choice===1);
 host.send({t:'h.settings',buildSec:30});host.send({t:'h.phase',phase:'build'});await host.wait(m=>m.t==='state'&&m.s.phase==='build');
 builder.send({t:'place',x:0,y:0,z:0,c:4});const ops=await host.wait(m=>m.t==='ops'&&m.team==='A');assert.equal(ops.ops[0][5],builder.you.id);manager.send({t:'remove',x:0,y:0,z:0});await host.wait(m=>m.t==='ops'&&m.team==='A'&&m.ops.some(o=>!o[0]));
 await host.wait(m=>m.t==='ops'&&m.team==='C');host.send({t:'h.pause'});await host.wait(m=>m.t==='state'&&m.s.pausedRemaining!==null);await delay(200);const paused=await app.connect();const before=Object.keys(paused.welcome.builds.C).length;assert.ok(before>0);assert.equal(paused.welcome.s.ai.plan,undefined);assert.equal(paused.welcome.s.ai.strategy,undefined);await delay(1200);const paused2=await app.connect();assert.equal(Object.keys(paused2.welcome.builds.C).length,before);host.send({t:'h.pause'});await host.wait(m=>m.t==='state'&&m.s.phase==='build'&&m.s.pausedRemaining===null&&m.s.serverNow>Date.now()-500);
 builder.send({t:'office.move',room:'arcade'});builder.send({t:'place',x:1,y:0,z:0,c:4});assert.match((await builder.wait('err')).msg,/回到自己的研發區/);await arrival(builder,'arcade');
 builder.send({t:'arcade.start',game:'pulse'});let game=(await builder.wait('arcade.round')).round;await delay(750);builder.send({t:'arcade.hit',round:game.id,tile:game.target});assert.equal((await builder.wait('arcade.round')).round.score,10);
 builder.send({t:'office.move',room:'lounge'});assert.match((await builder.wait('err')).msg,/才能離開/);await delay(20000);builder.send({t:'office.move',room:'lounge'});builder.send({t:'arcade.hit',round:game.id,tile:game.target});assert.match((await builder.wait('err')).msg,/抵達遊戲室/);
 host.send({t:'h.time',sec:30});await host.wait(m=>m.t==='state'&&m.s.ai.progress===100);const snapshot=await app.connect();assert.ok(Object.keys(snapshot.welcome.builds.C).length>100);assert.ok(snapshot.welcome.s.players.find(p=>p.id===builder.you.id).leisure.awaySeconds>0);
 host.send({t:'h.phase',phase:'review'});await host.wait(m=>m.t==='state'&&m.s.phase==='review');builder.send({t:'vote',team:'C'});assert.equal((await builder.wait(m=>m.t==='you'&&m.you.reviewVote==='C')).you.reviewVote,'C');peers[0].send({t:'bossPick',team:'C'});await host.wait(m=>m.t==='state'&&m.s.review.bossPick==='C');
 host.send({t:'h.phase',phase:'poster'});await host.wait(m=>m.t==='state'&&m.s.phase==='poster');maker.send({t:'poster',img:'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==',name:'NEXUS ONE',slogan:'共同想像未來',final:true});await host.wait(m=>m.t==='fx'&&m.kind==='posterDone');assert.equal((await fetch(app.base+'/poster/'+maker.you.id+'.jpg')).status,200);builder.send({t:'survey',price:16800,quote:'未來的座位'});await builder.wait(m=>m.t==='you'&&m.you.survey?.price===16800);
 host.send({t:'h.phase',phase:'gallery'});await host.wait(m=>m.t==='state'&&m.s.phase==='gallery');peers[0].send({t:'gpick',author:maker.you.id});await host.wait(m=>m.t==='state'&&m.s.gallery.bossPick===maker.you.id);host.send({t:'h.phase',phase:'launch'});const launch=(await host.wait(m=>m.t==='state'&&m.s.phase==='launch')).s;assert.equal(launch.launch.winner,'C');assert.equal(launch.launch.official,maker.you.id);assert.equal(launch.players.length,50);assert.equal((await fetch(app.base+'/api/results.zip?key=wrong')).status,403);assert.equal((await fetch(app.base+'/api/results.zip?key='+KEY)).status,200);
 host.send({t:'h.kick',id:peers[0].you.id});const kicked=(await host.wait(m=>m.t==='state'&&m.s.players.length===49)).s;assert.equal(kicked.board.chair,null);assert.equal(kicked.players.filter(p=>p.rank==='boss').length,0);
 fs.mkdirSync(path.join(__dirname,'../artifacts'),{recursive:true});fs.writeFileSync(path.join(__dirname,'../artifacts/game-verification.json'),JSON.stringify({passed:true,connections:50,release:'rog-city-2026.10.06',assertions:['no-self-vote','runoff','election','chair-only-core','movement','work-presence','arcade-score','AI-autonomous','AI-pause','AI-winner','poster','survey','gallery','export','chair-removal'],at:new Date().toISOString()},null,2));
});


