const {chromium}=require('playwright'),{start,KEY}=require('./helpers.cjs'),assert=require('assert/strict'),fs=require('fs');
(async()=>{fs.mkdirSync('artifacts',{recursive:true});const app=await start();let browser;const errors=[];try{
 browser=await chromium.launch({channel:'msedge',headless:true});const context=await browser.newContext({viewport:{width:1440,height:960}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 await page.goto(app.base+'/host?key='+KEY);await page.waitForSelector('#hostCue');await page.waitForSelector('#office canvas');await page.screenshot({path:'artifacts/host-ready.png'});
 assert.equal(await page.locator('#showTitle').textContent(),'報到集合');assert.equal(await page.locator('.intro-download').getAttribute('download'),'金桶公司_1分鐘前導說明.mp4');
 await page.locator('.meeting-audio summary').click();await page.locator('#soundToggle').click();await page.waitForFunction(()=>MeetingAudio.enabled&&MeetingAudio.ctx.state==='running');assert.equal(await page.evaluate(()=>MeetingAudio.music),.06);await page.locator('#soundToggle').click();await page.waitForFunction(()=>!MeetingAudio.enabled&&MeetingAudio.ctx.state==='suspended');await page.locator('#soundToggle').click();await page.waitForFunction(()=>MeetingAudio.enabled);await page.locator('.meeting-audio summary').click();
 await page.locator('#introStart').click();await page.waitForFunction(()=>document.querySelector('#introMovie').currentTime>.3);const video=await page.locator('#introMovie').evaluate(v=>({duration:v.duration,w:v.videoWidth,h:v.videoHeight}));assert.ok(video.duration>59&&video.duration<=61);assert.equal(video.w,1280);assert.equal(video.h,720);await page.locator('#introSkip').click();await page.waitForFunction(()=>document.querySelector('.intro-overlay').hidden);
 const response=await fetch(app.base+'/intro-60.mp4');assert.equal(response.headers.get('content-type'),'video/mp4');
 await page.locator('#showStart').click();await page.waitForSelector('#showRun:not([hidden])');assert.equal(await page.locator('#showClock').textContent(),'0:45');await page.locator('#showPause').click();await page.waitForFunction(()=>document.querySelector('#showPause').textContent==='繼續計時');await page.screenshot({path:'artifacts/host-show.png'});assert.ok((await page.locator('#showNext').textContent()).includes('董事互選'));
 const phone=await context.newPage({viewport:{width:390,height:844}});await phone.setViewportSize({width:390,height:844});phone.on('pageerror',e=>errors.push(e.message));await phone.goto(app.base);await phone.waitForSelector('.phase-cue:not([hidden])');assert.equal(await phone.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await phone.screenshot({path:'artifacts/show-phone.png'});await phone.close();
 const guide=await context.newPage();await guide.goto(app.base+'/game-guide.html#intro');await guide.waitForSelector('video');assert.equal(await guide.locator('video').count(),4);await guide.locator('video').first().evaluate(async v=>{v.muted=true;await v.play();});await guide.waitForFunction(()=>document.querySelector('video').currentTime>.3);assert.deepEqual(errors,[]);
 fs.mkdirSync('artifacts',{recursive:true});fs.writeFileSync('artifacts/show-visual-verification.json',JSON.stringify({passed:true,video,errors,checks:['host large cues','download MP4','audio start/mute/resume','intro playback','600-second mode start/pause','mobile no overflow','guide video decode']},null,2));console.log('PASS host, mobile, audio, MP4 and guide');
}finally{await browser?.close();await app.stop();}})().catch(e=>{console.error(e);process.exitCode=1;});
