'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),G=require('../public/shared.js'),{start,KEY,delay,join50}=require('./helpers.cjs');
test('ten-minute show has authoritative timers, access control, pause, election hold and complete sequence',{timeout:120000},async t=>{
 assert.equal(G.SHOW_PLAN.reduce((n,p)=>n+p.seconds,0),600);const app=await start();t.after(()=>app.stop());const host=await app.connect({host:true,key:KEY}),visitor=await app.connect();visitor.send({t:'h.startShow'});await delay(250);assert.equal((await app.connect()).welcome.s.show,null);
 host.send({t:'h.intro'});const intro=(await host.wait(m=>m.t==='state'&&m.s.intro)).s.intro;assert.equal(intro.endsAt-intro.startedAt,60000);host.send({t:'h.stopIntro'});await host.wait(m=>m.t==='state'&&!m.s.intro);
 const {peers,state}=await join50(app,host);host.send({t:'h.startShow',auto:true});let s=(await host.wait(m=>m.t==='state'&&m.s.show?.active)).s;assert.equal(s.phase,'lobby');assert.equal(s.phaseEndsAt-s.phaseStartedAt,45000);assert.equal(s.settings.buildSec,210);
 host.send({t:'h.pause'});s=(await host.wait(m=>m.t==='state'&&m.s.pausedRemaining!=null)).s;const left=s.pausedRemaining;await delay(500);assert.equal((await app.connect()).welcome.s.pausedRemaining,left);host.send({t:'h.pause'});await host.wait(m=>m.t==='state'&&m.s.pausedRemaining===null&&m.s.show?.active);
 const end=async phase=>{host.send({t:'h.endNow'});return (await host.wait(m=>m.t==='state'&&m.s.phase===phase)).s;};s=await end('roles');assert.equal(s.phaseEndsAt-s.phaseStartedAt,30000);host.send({t:'h.endNow'});s=(await host.wait(m=>m.t==='state'&&m.s.show?.hold)).s;assert.equal(s.phase,'roles');assert.equal(s.board.chair,null);assert.equal(s.timeUp,true);
 peers[1].send({t:'board.vote',candidate:peers[0].you.id,round:state.board.round});peers[2].send({t:'board.vote',candidate:peers[0].you.id,round:state.board.round});await host.wait(m=>m.t==='state'&&m.s.board.chair===peers[0].you.id);host.send({t:'h.next'});s=(await host.wait(m=>m.t==='state'&&m.s.phase==='brief')).s;assert.equal(s.show.hold,null);assert.equal(s.phaseEndsAt-s.phaseStartedAt,45000);
 s=await end('build');assert.notEqual(s.brief.choice,null);assert.equal(s.phaseEndsAt-s.phaseStartedAt,210000);s=await end('review');assert.equal(s.phaseEndsAt-s.phaseStartedAt,60000);
 host.send({t:'h.autoShow',auto:false});await host.wait(m=>m.t==='state'&&m.s.show?.auto===false);host.send({t:'h.endNow'});s=(await host.wait(m=>m.t==='state'&&m.s.phase==='review'&&m.s.timeUp)).s;assert.equal(s.phase,'review');host.send({t:'h.next'});s=(await host.wait(m=>m.t==='state'&&m.s.phase==='poster')).s;assert.equal(s.phaseEndsAt-s.phaseStartedAt,120000);host.send({t:'h.autoShow',auto:true});await host.wait(m=>m.t==='state'&&m.s.show?.auto===true);
 s=await end('gallery');assert.equal(s.phaseEndsAt-s.phaseStartedAt,45000);s=await end('launch');assert.ok(s.launch.finance);host.send({t:'h.endNow'});s=(await host.wait(m=>m.t==='state'&&m.s.show?.completedAt)).s;assert.equal(s.show.active,false);
 fs.mkdirSync('artifacts',{recursive:true});fs.writeFileSync('artifacts/show-verification.json',JSON.stringify({passed:true,connections:50,totalSeconds:600,introSeconds:60,assertions:['host-only','pause-resume','two-vote-election-hold','no-auto-voting','automatic-sequence','manual-mode','launch-finished'],at:new Date().toISOString()},null,2));
});
